---
title: "Explainers"
subtitle: "Notes for contributors"
---
On Real World Data Science, **Explainers** are the stories behind the stories of data science in action. They are deep-dive explorations of the ideas, concepts, tools, and methods that make data science projects possible. In particular, we are keen to explore and explain the statistical underpinnings of modern data science techniques. 

A good Explainer will lead audiences through the what, when, how, and why of its chosen topic. The ultimate goal is to equip data scientists with the information and insight they need to make smarter, more informed analytical choices. 

There are many different but effective ways of structuring an explainer and plentiful written examples in major media outlets like [The Guardian](https://www.theguardian.com/tone/explainers) and [Vox](https://www.vox.com/explainers), but these are generally written for a non-technical audience. Examples of technical explainers (with interactive elements) can be found on Amazon’s [Machine Learning University](https://mlu-explain.github.io/).  

## Structure
The following outline is a basic guide to structuring an Explainer: 

* Hook 
: Introduce your topic, and explain why audiences should pay attention. For example, does your Explainer link to one of our published [case studies](case-studies.qmd)? Does it focus on a tool or method that has been the subject of recent attention? Is it a foundational idea that is relevant to all sorts of data science applications? 

* High-level summary 
: A short, largely non-technical explanation of your topic. A good way to view this section is as an accessible condensed version of your complete Explainer. In thinking of it in this way, you can subtly signpost to audiences the areas you’ll be covering and the questions you’ll be answering throughout the remainder of your contribution. 

* History and background 
: It can be useful from a practical perspective to explain how ideas, concepts, tools, and methods have developed over time. Applications may have become more complex in recent years, so exploring the origins of data science techniques might lead you to discover simpler use cases that can help support and illustrate your high-level summary. 

* The how, the when, the why 
: This section of your Explainer will likely be split into multiple subsections as you seek to build up your audience's understanding of your chosen topic. It can be helpful to think about the sorts of questions an audience member might ask and to structure your contribution so that it directly addresses those questions (Q&A/FAQ formats are commonly used in explainer-type articles). If the focus of your Explainer is a data science method, for example, you’ll want to address the following:

  + How does it work and how is it applied (perhaps with an example or simulation)? 
  + What are the underlying assumptions? 
  + How is performance checked and assessed? 
  + How should outputs be interpreted? 
  + What are the pros and cons, the strengths and limitations of the approach? 
  + What are the optimal use cases, and when should the method be avoided altogether? 
  + Are there alternatives that people should know about? 

* Key takeaways 
: This serves as your final summary: a chance to remind your audience of what they’ve learned from your Explainer and the main points they should keep in mind.   

* Tell me more 
: It’s sensible to assume that some of your audience will have further questions and will want to learn more about the topic. If you have additional sources of information to recommend, make sure to share them here.      

## Advice and recommendations 
*Focus on what’s important.* Your Explainer can’t hope to explain everything, so you need to be clear about what’s essential for your audience to know and what isn’t. Make good use of links and references to point audiences to other valuable sources of information that can enrich their understanding of your topic. 

*Be clear about your target audience and their expected prior level of knowledge.* In keeping with the point above, you need to be clear in your own mind about how much you expect your audience to know already about the general topic or subject matter. You can then structure your contribution accordingly. It might also be helpful to state explicitly, at the outset of your contribution, what assumptions you’ve made about your audience and highlight any background reading that might be beneficial. 

*Plan out your route.* To help you decide what to cover in your Explainer, we recommend first writing out your high-level summary of the topic and also your key takeaways. This provides you with a start point (A) and an end point (B) for your contribution. The challenge then is to figure out the main points or questions you will need to address to help your audience progress from point A to point B in a way that's logical and intuitive for them to follow.