---
title: "Recommenders"
subtitle: "Notes for contributors"
---
Too much content, not enough time. That about sums up the problem facing the data science community. So, our **Recommenders** are here to help. Contributors are invited to submit lists (or **Feeds**) of high-quality sources on all manner of topics -- from foundational ideas in data science and cutting-edge techniques, to opinion and thought-leadership on the future of the profession. **Reviews** of new books and other material are also welcome. 

## Article types and structures 

### Feeds 
Feeds can be constructed around different topics and audiences. For example, you might want to recommend to all data scientists the “10 best blogs on machine learning” or “5 data visualisation experts to follow on Twitter/X”. Or you might have a list of sources specifically targeted at data science educators (e.g., “the best books on teaching coding”) or data science leaders (“5 insightful case studies on building data science teams”).  

Whatever you choose to focus on, the following outline provides a basic guide for structuring your feed: 

* Overview 
: A brief introduction to your list, its main focus, who you are writing it for, and why. You should also say something about yourself and your background, too. This will give additional context to the recommendations you are making. 

* List of sources 
: As well as naming your sources and telling people how to find them, you should also explain why you are recommending them, how they helped you in your career or studies, or other reasons why you find them to be of value. Sample quotes or small excerpts from the sources themselves might also be worth including. 

* Start a dialogue 
: Conclude with a call for readers to share recommendations of their own, either in the article comments or on social media. Contributors are welcome to update their lists any time with new sources, including those suggested by site users.  

### Reviews 
Unlike the feeds described above, each submitted review should focus only on a single publication. It must be an honest summary of the reviewer’s thoughts, feelings and impressions, covering what they liked and didn’t like, the perceived strengths and weaknesses of the publication, and whether it is likely to be of interest and value to its intended audience. Reviews should of course provide an overview of the publication in question but must avoid dry, itemised descriptions of the publication’s constituent parts (e.g., listing out the chapters in a book).   

All reviews should list the following information (if relevant): 

* Title of publication 
* Author(s) 
* Date of publication 
* Edition or format used for review 
* Publisher 
* Length 
* Price 
* Website address or other source of further information 

## Advice and recommendations 

*Keep lists to a sensible size.* Feeds are meant to help data scientists to prioritise who and what to follow based on their interests and career stage -- and it is much easier to keep tabs on 5 sources than it is 50, or even 15! So, the fewer the better. 

*Keep your recommendations up to date.* In this era of digital publishing, things can and do change overnight. So, if one of your recommended bloggers stops blogging, or the author of one of your favourite books makes a major update to the text, do be sure to let us -- and your audience -- know. We want to keep feeds and reviews current and useful. 

*Of course you are brilliant, but...* Please do not recommend or review your own publications or those in which you have a pecuniary or similar interest. 