---
title: "Training guides"
subtitle: "Notes for contributors"
---
In data science, there's no one-size-fits-all solution to every problem and challenge. So, part of the job of the data scientist is to rapidly learn about different sub-domains, tools and techniques, and put those learnings into practice.  

But it can be time-consuming to figure out what you need to learn and in what order, and to identify the best resources for doing so. This is where our **Training guides** come in. Each will set out a learning pathway for data scientists to follow, with recommendations of textbooks, videos, practical exercises and other teaching material to use every step of the way. 

## Structure 

Contributors should think about their training guides as being short online courses that are constructed from existing high-quality material. You do not need to create your own “course” content. Rather, you should focus on recommending texts and other material for users to follow in a logical ordered way, so that they may build up and secure their knowledge of a particular topic. 

Guides should feature a mix of content types -- not only text, but audio and video -- and they should provide ample opportunities for users to practice what they are learning.  

A brief and extremely simplified example of a guide is as follows: 

* **Step 1:** Watch this introductory video on Topic X. 

* **Step 2:** Now you are familiar with the basics of Topic X, you will want to read Chapter 2 of Textbook Y, which delves into more of the mathematical underpinnings. 

* **Step 3:** Let’s try Topic X ourselves. This GitHub repository has code for you to run it in Python. Copy the code and give it a go. 

* **Step 4:** You should now be ready to apply Topic X to a simple data challenge. Check out this Kaggle page and practice what you have learned so far. 

* **Step 5:** We’re now moving from the “beginner” level to “intermediate”, and Training Course Z gives a thorough overview of what you need to know for the next stage of your learning journey. 

* … etc. 

## Advice and recommendations 

*Be mindful of different learning styles.* Some people prefer to read, others prefer to watch or listen. So, wherever possible, for each stage of your training guide, try to provide a mix of resources that meet the same learning objectives. 

*Consider barriers to entry.* Data scientists in large organisations may have access to training budgets or mechanisms to apply for training funds. But that isn’t the case for all data scientists, meaning that paid-for materials and training courses might not be accessible to everyone. Recommend them sparingly, and if there are ways to access the material at reduced rates do let users know. However, you must not link to illicit copies of material -- e.g., unauthorised PDF reproductions of textbooks.  

*If there are resource gaps, please tell us.* While planning out your training guide, you may well struggle to find the perfect piece of content to recommend at a particular stage of your learning journey. If that is the case, do get in touch with us. One of the goals of Real World Data Science is to identify and plug these sorts of gaps, so that all in the data science community can benefit. We’ll sketch out a commission and take it out to our network of contacts. Or perhaps it’ll be something you want to create for the site!