---
title: "A showcase for data science in action"
sidebar: false
listing:
  - id: blogs
    contents: 
    - /news-and-views/editors-blog
    - /news-and-views/datasciencebites
    - "!index.qmd"
    sort: "date desc"
    type: default
    categories: false
    sort-ui: false
    filter-ui: false
    max-items: 3
    feed: false
---

Welcome to the home of **Real World Data Science**, a new project from the [Royal Statistical Society](https://rss.org.uk/). This site and its content are being created and curated by data science practitioners and leaders with a single goal in mind: to help you deliver high quality, ethical, impactful data science in your workplace.

::: {.callout-note appearance="simple" collapse="false"}
## Latest updates 

::: {#blogs}
::: 

:::

## What are our aims?
Real World Data Science aims to be a trusted, go-to source for high-quality, engaging and inspiring content which helps data science students, practitioners and leaders to: 

* discover and learn more efficiently;  
* acquire practical problem-solving skills;  
* share their knowledge and accomplishments publicly;  
* work smarter, ethically, and more effectively.  

## What will we provide?
Resources will be *created* to meet the needs of our target audiences. These include: 

* **Case studies** – showing how data science is used to solve real-world problems in business, public policy and beyond. 
* **Explainers** – interrogating the underlying assumptions and limitations of data science tools and methods, to help data scientists make smarter, more informed analytical choices.
* **Exercises** – to challenge and develop the analytical mindset that all data scientists need to succeed.    
* **Advice** – interviews, Q&As, and FAQs on such topics as data science ethics, career paths, and communication, to support professional development. 

Resources will also be *curated* to help data scientists identify trustworthy, high-quality content. These include: 

* **Training guides** – step-by-step approaches and recommended sources for learning new skills and methods. 
* **Datasets** – tagged and sorted to help educators and practitioners find data to meet their teaching and training needs. 
* **Feeds** – who and what to follow to keep up with new ideas and developments.

## How you can get involved
See our open [call for contributions](contributor-docs/call-for-contributions.qmd).
